langOverwrite: true
defaultLanguage: "ja_jp"
mysql:
  host: localhost
  port: 3306
  pass: pass
  user: root
  db: identity
discord:
  enabled: false
  autoStart: false
  token: ???
  commandChannel: ???
  infoChannel: ???
  entryPermission: ???
  opPermission: ???
  guild: ???
  map: ???