name: IdentityFifty
version: '${version}'
main: tororo1066.identityfifty.IdentityFifty
api-version: 1.17

depend:
  - GlowAPI
  - WorldGuard
  - WorldEdit
  - LibsDisguises

softdepend:
  - NMSUtils

commands:
  identity: